# Generated by Django 2.2 on 2019-04-24 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Авторы', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанр'},
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Картина')),
                ('file', models.FileField(upload_to='file/%Y/%m/%d', verbose_name='Книга')),
                ('size', models.CharField(blank=True, max_length=255, verbose_name='Размер файла')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_book', to='books.Author', verbose_name='Автор')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_book', to='books.Genre', verbose_name='Жанр')),
            ],
        ),
    ]
