# Generated by Django 2.2 on 2019-04-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190424_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
