# Generated by Django 2.2 on 2019-04-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190424_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['date'], 'verbose_name': 'Книги', 'verbose_name_plural': 'Книги'},
        ),
    ]
