# Generated by Django 2.2 on 2019-04-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Есімініз')),
                ('email', models.EmailField(max_length=254, verbose_name='Электрондық почтаныз')),
                ('subject', models.CharField(max_length=255, verbose_name='Хат атауы')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
